[package]
name = "ghostloader"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
ring = "0.17.14"
libc = "0.2.176"
tokio = { version = "1.47.1", features = ["full"] }
zeroize = "1.8.2"
rand = "0.10.0-rc.0"
sha2 = "0.11.0-rc.2"
hex = "0.4.3"
base64 = "0.22.1"
hostname = "0.4.1"